version: "3.8"

services:
  eleventy:
    container_name: suraj_portfolio
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    entrypoint:
      - yarn
      - run
      - serve
