name: build page

on:
  workflow_dispatch:
  repository_dispatch: # build on diary_push
    types: [diary_push, posts_push, fragments_push]
  push:
    branches:    
      - master 

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
        fetch-depth: 0
        
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    
    - name: yarn install
      run: |
        yarn install

    - name: Pull latest submodules
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote
        
    - name: yarn build
      run: |
        yarn run build

    # - name: Deploy
    #   uses: JamesIves/github-pages-deploy-action@v4.2.5
    #   with:
    #     branch: gh-pages # The branch the action should deploy to.
    #     folder: docs # The folder the action should deploy.

    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          email: ysuraj877@gmail.com
          build_dir: docs
          branch: gh-pages
          jekyll: no                     
          commit_message: build pushed to gh-pages
