name: build & deploy to pages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    uses: actions/checkout@v1
    - name: Use Node.js 14.18.1
      uses: actions/setup-node@v1
      with:
        node-version: 14.18.1

      - name: yarn install
        run: |
          yarn install
      - name: yarn build
        run: |
          yarn build
      - name: list pwd
        run: |
          echo pwd
        
